FROM --platform=linux/amd64 nginx:latest

COPY ./frontend/dist /usr/share/nginx/html

RUN rm -rf /etc/nginx/conf.d/default.conf
COPY ./frontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]