apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3 # Number of replicas you want
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: my-nginx-container
          image: docker.io/patrickuuuu/grapycal-frontend:latest
          ports:
            - containerPort: 80
