[tool.poetry]
name = "grapycal"
version = "0.2.0"
description = ""
authors = ["eri24816 <a931eric@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
objectsync = { git = "https://github.com/eri24816/ObjectSync.git", branch = "master"}
pyyaml = "^6.0"
dacite = "^1.8.1"
usersettings = "^1.1.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
