apiVersion: apps/v1
kind: Deployment
metadata:
  name: grapycal-backend
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: grapycal-backend
      env: docker-desktop
  template:
    metadata:
      labels:
        app: grapycal-backend
        env: docker-desktop
    spec:
      containers:
        - name: grapycal-container
          image: docker.io/patrickuuuu/grapycal-backend:latest
          ports:
            - containerPort: 8765

---

apiVersion: v1
kind: Service
metadata:
  name: grapycal-service
  namespace: default
spec:
  selector:
    app: grapycal
    env: docker-desktop
  ports:
    - protocol: TCP
      port: 8765
      targetPort: 8765
  type: LoadBalancer