apiVersion: v1
kind: Service
metadata:
  name: grapycal-service
spec:
  selector:
    app: grapycal
  ports:
    - protocol: TCP
      port: 8765
      targetPort: 8765
  type: LoadBalancer # Use NodePort or ClusterIP for different types of access
