name: Frontend CI

on:
    push:
        branches: [main, dev]
    pull_request:
        branches: [main, dev]

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                node-version: 20
                cache: 'npm'
                cache-dependency-path: frontend/package-lock.json
            - name: Build the app
              run: |
                cd frontend && npm ci && npm run build:service
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Set up containerd
              uses: crazy-max/ghaction-setup-containerd@v3
            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Build Docker image
              uses: docker/build-push-action@v4
              with:
                context: .
                file: ./Dockerfile.frontend
                platforms: linux/amd64,linux/arm64
                tags: docker.io/${{ secrets.DOCKER_USERNAME }}/grapycal-frontend:latest
                outputs: type=oci,dest=/tmp/image.tar
                build-args: |
                  NODE_VERSION=20
            - name: Import image in containerd
              run: |
                sudo ctr i import --base-name docker.io/${{ secrets.DOCKER_USERNAME }}/grapycal-frontend:latest --digests --all-platforms /tmp/image.tar
            - name: Push image to containerd
              run: |
                sudo ctr i push --user "${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWORD }}" docker.io/${{ secrets.DOCKER_USERNAME }}/grapycal-frontend:latest